#Write a program that declares an integer and initializes it to a five-digit number. It prints the sum of the digits of the integer.
#Extend the program to check if the number is divisible by 11. For this purpose you should check the divisibility in two ways. Suppose the number is 12345.
#The program should print the following three lines.

#   	Sum of digits of 12345 is 15.
#	When divided by 11, 12345 leaves remainder 3.
#	The alternate digit sums of 12345 are 9 and 6. Divisibility by 11: false.
#The third line is generated by using the standard divisibility test of 11 where you compute the sums of the alternate digits.
#The number is divisible by 11 iff the difference of the sums is divisible by 11

num = 54321
num1 = str(num)
num2 = 0
list1 = []
rem = num%11
for i in num1:
    num2 += int(i)
    list1.append(int(i))
print ("Sum of digits of", num, "is",num2)
print ("When divided by 11,", num,"leaves remainder", rem)
even = list1[::2]
odd = list1[1::2]
sum_even = sum(even)
sum_odd = sum(odd)
if sum_even > sum_odd:
    div = sum_even-sum_odd
else:
    div = sum_odd-sum_even

if div%11==0 or div ==0:
    print("The alternate digit sums of %s are %s and %s. Divisibility by 11: True." %(num,sum_even,sum_odd))
else:
    print("The alternate digits sums of %s are %s and %s. Divisibility by 11: False." %(num,sum_even,sum_odd))
    
